### ISSUE TITLE
Tile Size Issue

### ISSUE THREAD

**Issue by protestToViolence** [iamtekson/geotile#10]
In this line of code,
gt.generate_tiles(r'/path/to/output/folder', tile_x=256, tile_y=256, stride_x=256, stride_y=256)

i am not able to change the tile size to 64 . It takes 256 only...What can be the reason?

Thank you,

**Comment by iamtekson** [comment]
Hi @protestToViolence, this is actually a bug I just corrected it. Thank you very much for reporting it. Please try to install the 0.2.4 version and it will solve the issue.
