### ISSUE TITLE
ModuleNotFoundError: No module named 'geotile'

### ISSUE THREAD

**Issue by Aerius42** [iamtekson/geotile#6]
Hi !

When I import geotile, following the readme `from geotile import GeoTile` gives me:
`ModuleNotFoundError: No module named 'geotile'`

I figured out that geotile is actually registered as **geoTile** so `from geoTile import GeoTile` works.

Thank you for your work by the way !

**Comment by iamtekson** [comment]
Hi @Aerius42, I think you are using v0.1.x version. I change the folder structure on v0.2.x. Can you try it with the latest version?

```shell
pip install geotile==0.2.2
```
