### ISSUE TITLE
conda installation of geotile in ubuntu 20.04

### ISSUE THREAD

**Issue by protestToViolence** [iamtekson/geotile#8]
ModuleNotFoundError: No module named 'geotile'
I am getting this error while executing the example that has been mentioned in the git profile.

Please help.

**Comment by Samlewis99** [comment]
2nd

**Comment by iamtekson** [comment]
I am working on this issue and it will solve today. Thank you for reporting.

**Comment by iamtekson** [comment]
Now the issue has been solved with the latest version of geotile package (v0.2.3). Make sure to install the latest version.
